config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: 'inventories#index', as: :authenticated_root
    end

    unauthenticated :user do
      root to: "devise/sessions#new", as: :unauthenticated_root
    end
  end

  resources :recipes do
    resources :recipe_foods
  end

  resources :inventories do
    resources :inventory_foods
  end

  get 'shopping_list', to: 'recipes#shopping_list', as: 'shopping_list'
  
  resources :foods
  resources :public_recipes, only: %i[index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :read, Inventory
    can :read, Recipe
    can :manage, Inventory, user_id: user.id
    can :manage, Recipe, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :inventory_foods
  has_many :inventories, through: :inventory_foods
  has_many :recipe_foods
  has_many :recipes, through: :recipe_foods
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods
  has_many :foods, through: :inventory_foods
end

app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
  belongs_to :food
  belongs_to :inventory
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods

  validates :name, presence: true
  validates :cooking_time, presence: true
  validates :preparation_time, presence: true
  validates :description, presence: true
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :inventories
  has_many :foods
  has_many :recipes
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]
  # GET /foods or /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)
    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_path, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :unit_quantity)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  load_and_authorize_resource

  def index
    @inventories = Inventory.all
  end

  def show
    @inventory = Inventory.includes(inventory_foods: :food).find(params[:id])
    @inventory_id = @inventory.id
    @inventories = Inventory.all

    render :show
  end

  def new
    @inventory = Inventory.new
  end

  def create
    @inventory = Inventory.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to inventory_path(@inventory), notice: 'Inventory created succesfully!' }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { redirect_to new_inventory_path, alert: 'Inventory not created!' }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @inventory = Inventory.find(params[:id])
    if @inventory.destroy
      flash[:notice] = 'Inventory deleted successfully!'
    else
      flash[:alert] = 'Inventory not deleted!'
    end
    redirect_to inventories_path
  end

  def shopping_list
    recipe_id = params[:recipe_id]
    params[:inventory_id]

    @inventory = recipe_id
  end

  private

  def inventory_params
    params.require(:inventory).permit(:name, :cooking_time, :preparation_time, :description, :status, :user_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.includes(recipe_foods: :food).find(params[:id])
    @recipe_id = @recipe.id
    @inventories = Inventory.all

    render :show
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_path(@recipe), notice: 'Recipe created succesfully!' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { redirect_to new_recipe_path, alert: 'Recipe not created!' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    if @recipe.destroy
      flash[:notice] = 'Recipe deleted successfully!'
    else
      flash[:alert] = 'Recipe not deleted!'
    end
    redirect_to recipes_path
  end

  def shopping_list
    @recipe_id = params[:recipe_id]
    @inventory_id = params[:inventory_id]

    @recipe = Recipe.includes(recipe_foods: :food).find(@recipe_id)
    @inventory = Inventory.find(@inventory_id)

    inventory_foods_id = @inventory.foods.pluck(:id)
    @missing_foods = @recipe.recipe_foods.reject { |food_recipe| inventory_foods_id.include?(food_recipe.food_id) }
  end

  def update
    @recipe = Recipe.find(params[:id])

    flash[:alert] = 'Not updated!' unless @recipe.update(recipe_params)
    redirect_to recipe_path(@recipe)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :cooking_time, :preparation_time, :description, :public, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/inventory_foods_helper.rb
module InventoryFoodsHelper
end

app/helpers/ppublic_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/inventories/_form.html.erb
<%= form_with(model: inventory) do |form| %>
  <% if inventory.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
        <% inventory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/inventories/_inventory.html.erb
<div id="<%= dom_id inventory %>">
</div>

app/views/inventories/edit.html.erb
<h1>Editing inventory</h1>

<%= render "form", inventory: @inventory %>

<br>

<div>
  <%= link_to "Show this inventory", @inventory %> |
  <%= link_to "Back to inventories", inventories_path %>
</div>

app/views/inventories/index.html.erb
<% @inventories.each do |item|%>
<div class="container">
 <div class="row border border-2 p-3 mb-3">
 <div class="col-4">
 
 <%= link_to item.name, item, class: 'nav-link'%>
 <% if can? :destroy, item %><%= link_to 'REMOVE', [item], method: :delete, data: {confirm: 'Are you sure!'}, class: 'fs-6 text-decoration-none' %><%end%>
 </div>
 <div class="col-8">
  <%= item.description%>
 </div>
 </div>
</div>
<%end%>
<%= link_to 'New Inventory', new_inventory_path(@inventory), class: 'btn btn-outline-dark btn-sm'%>

app/views/inventories/new.html.erb
<br>
<h2 class="text-center">Add New Inventory</h2>
<br>
<%= form_with model: @inventory do |f| %>

	<br>
	<div>
		<%= f.label :name %>
		<%= f.text_field :name, autofocus: true, autocomplete: 'name', placeholder: 'name', class: 'form-control' %>
	</div>
	<br>
	<div>
		<%= f.label :Description %>
		<%= f.text_area :description, autofocus: true, autocomplete: 'description', placeholder: 'description', class: 'form-control' %>
	</div>
	<br>
	<div>
		<%= f.number_field :user_id, value: current_user.id, type: :hidden %>
	</div>
	<br>
	<div>
		<%= f.submit class: 'btn btn-outline-dark btn-sm' %>
	</div>
<% end %>

app/views/inventories/show.html.erb
<h2><%= @inventory.name%></h2>
<%= link_to 'Add Food', new_inventory_inventory_food_path(inventory_id: @inventory_id), class: 'btn btn-outline-dark btn-sm' %>
<hr>
<table class="table table-striped table-bordered">
		<% if @inventory.inventory_foods.any? %>
			<thead>
				<tr>
					<th scope="col">Food</th>
					<th scope="col">Quantity</th>
					<th scope="col">Actions</th>
				</tr>
			</thead>
			<tbody>
			<% @inventory.inventory_foods.each do |food_recipe| %>
				<tr>
					<td><%=food_recipe.food.name %></td>
					<td><%=food_recipe.quantity %> <%=food_recipe.quantity_unit %></td>
					<td>

      			<%= link_to 'Remove', inventory_inventory_food_path(@inventory, id: food_recipe), method: :delete, data: { confirm: 'Are you sure?' } %>
					</td>
				</tr>
			<% end %>
			</tbody>
		<% end %>
	</table>