config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: 'inventories#index', as: :authenticated_root
    end

    unauthenticated :user do
      root to: "devise/sessions#new", as: :unauthenticated_root
    end
  end

  resources :recipes do
    resources :recipe_foods
  end

  resources :inventories do
    resources :inventory_foods
  end

  get 'shopping_list', to: 'recipes#shopping_list', as: 'shopping_list'
  
  resources :foods
  resources :public_recipes, only: %i[index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :read, Inventory
    can :read, Recipe
    can :manage, Inventory, user_id: user.id
    can :manage, Recipe, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :inventory_foods
  has_many :inventories, through: :inventory_foods
  has_many :recipe_foods
  has_many :recipes, through: :recipe_foods
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods
  has_many :foods, through: :inventory_foods
end

app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
  belongs_to :food
  belongs_to :inventory
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods

  validates :name, presence: true
  validates :cooking_time, presence: true
  validates :preparation_time, presence: true
  validates :description, presence: true
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :inventories
  has_many :foods
  has_many :recipes
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]
  # GET /foods or /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)
    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_path, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :unit_quantity)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/inventories_contoller.rb
class InventoriesController < ApplicationController
  load_and_authorize_resource

  def index
    @inventories = Inventory.all
  end

  def show
    @inventory = Inventory.includes(inventory_foods: :food).find(params[:id])
    @inventory_id = @inventory.id
    @inventories = Inventory.all

    render :show
  end

  def new
    @inventory = Inventory.new
  end

  def create
    @inventory = Inventory.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to inventory_path(@inventory), notice: 'Inventory created succesfully!' }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { redirect_to new_inventory_path, alert: 'Inventory not created!' }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @inventory = Inventory.find(params[:id])
    if @inventory.destroy
      flash[:notice] = 'Inventory deleted successfully!'
    else
      flash[:alert] = 'Inventory not deleted!'
    end
    redirect_to inventories_path
  end

  def shopping_list
    recipe_id = params[:recipe_id]
    params[:inventory_id]

    @inventory = recipe_id
  end

  private

  def inventory_params
    params.require(:inventory).permit(:name, :cooking_time, :preparation_time, :description, :status, :user_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.includes(recipe_foods: :food).find(params[:id])
    @recipe_id = @recipe.id
    @inventories = Inventory.all

    render :show
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_path(@recipe), notice: 'Recipe created succesfully!' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { redirect_to new_recipe_path, alert: 'Recipe not created!' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    if @recipe.destroy
      flash[:notice] = 'Recipe deleted successfully!'
    else
      flash[:alert] = 'Recipe not deleted!'
    end
    redirect_to recipes_path
  end

  def shopping_list
    @recipe_id = params[:recipe_id]
    @inventory_id = params[:inventory_id]

    @recipe = Recipe.includes(recipe_foods: :food).find(@recipe_id)
    @inventory = Inventory.find(@inventory_id)

    inventory_foods_id = @inventory.foods.pluck(:id)
    @missing_foods = @recipe.recipe_foods.reject { |food_recipe| inventory_foods_id.include?(food_recipe.food_id) }
  end

  def update
    @recipe = Recipe.find(params[:id])

    flash[:alert] = 'Not updated!' unless @recipe.update(recipe_params)
    redirect_to recipe_path(@recipe)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :cooking_time, :preparation_time, :description, :public, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/inventory_foods_helper.rb
module InventoryFoodsHelper
end

app/helpers/ppublic_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/_food.html.erb
<div class="row">

  <div class="col-12 col-md-6 mb-3">
    <span class="badge bg-dark">Food</span>
    <h1><%= food.name %></h1>
  </div>

  <div class="col-6 col-md-3 text-center mb-3">
    <span class="badge bg-dark">Price</span>
    <p><%= food.price %></p>
  </div>
</div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% grouped_options = [
    [
      'Liquids',
      [
        ['Gallon', 'gal.'],
        ['Quart', 'qt.'],
        ['Liters', 'lt'],
        ['Mililiters', 'ml.'],
        ['Ounces', 'oz.'],
      ]
    ],
    [
      'Units',
      [
        ['Dozen', 'dz.'],
        ['Cup', 'c.'],
        ['Piece', 'pz.'],
        ['Table Spoon', 'tbsp'],
        ['Tea Spoon', 'tsp.'],
        ['Unit', 'ut.'],
      ]
    ],
    [
      'Weight',
      [
        ['Grams', 'g.'],
        ['Kilograms', 'kg.'],
        ['Pounds', 'lb.'],
      ]
    ],
  ] %>  

  <% if food.errors.any? %>
    <div style='color: red'>
      <h2><%= pluralize(food.errors.count, 'error') %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">

    <div class="col-12 mb-3">
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control', placeholder: 'Enter a food', required: true %>
    </div>

    <div class="col-12 col-md-6 mb-3">
      <%= form.label :measurement_unit, class: 'form-label' %>
      <%= form.select :measurement_unit, 
        grouped_options_for_select(grouped_options),
        {include_blank: 'Select'},
        class: 'form-select',
        required: true
      %>
    </div>

    <div class="col-12 col-md-3 mb-3">
      <%= form.label :price, class: 'form-label' %>
      <%= form.text_field :price, class: 'form-control', step: "any", required: true %>
      <span class="comment">Price for unit</span>
    </div>      

    <div class='col-12 mt-3 text-end'>
      <%= form.submit 'Save', class: 'btn btn-primary text-light ms-3' %>
    </div>
  </div>
<% end %>

app/views/foods/edit.html.erb
<div class="container mt-2">
  <h1>Edit food</h1>
  <%= render "form", food: @food %>
  <div>
    <%= link_to "< Back to foods", foods_path %> |
    <%= link_to "Show this food", @food %>
  </div>
</div>

app/views/foods/index.html.erb
<div class="mb-3">
<div>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Food</th>
      <th>Measurement unit</th>
      <th>Unit price</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
  <% @foods.each do |food|%>
    <tr>
      <td><%=food.name%></td>
      <td><%=food.measurement_unit%> <%=food.unit_quantity%></td>
      <td>$<%=food.measurement_unit * food.price%></td>
      <td><%= link_to "Delete",[food], method: :delete, data: {confirm: 'Are you sure!'} %></td>
    </tr>
  <%end%>
  </tbody>
</table>
</div>
<%= link_to "Add Food", new_food_path, class: "btn btn-outline-dark btn-sm" %>
</div>

app/views/foods/new.html.erb
<%= form_with(model: @food) do |form| %>
  <% if @food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>
      <ul>
        <% @food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <br>
  <div>
    <%= form.label :measurement_unit, "Measurement unit" %>
    <%= form.number_field :measurement_unit, class: 'form-control' %>
  </div>
  <br>
  <div>
    <%= form.label :unit_quantity, "Units" %>
    <%= form.text_field :unit_quantity, class: 'form-control' %>
  </div>
  <br>
  <div>
    <%= form.label :price %>
    <%= form.text_field :price, class: 'form-control' %>
  </div>
  <br>
  <div>
    <%= form.submit class: 'btn btn-outline-dark btn-sm' %>
  </div>
<% end %>

app/views/foods/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <%= render @food %>

  <div class="row">
    <div class="col-12 col-md-6">
      <%= link_to "< Back to foods", foods_path %> 
      <%if can? :edit, @food%>
        |
        <%= link_to "Edit this food", edit_food_path(@food) %> 
      <%end%>

    </div>
    <%if can? :destroy, @food%>
      <div class="col-12 col-md-6 text-end">
        <%= button_to "Delete", @food, method: :delete, class: 'btn btn-danger text-light' %>
      </div>
    <%end%>
    
  </div>
</div> 

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, class: "c-new-recipe-form c-card") do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="c-new-recipe-form__upload">
    <img class="c-new-recipe-form__img" src=<%= image_url("recipe_placeholder.jpg") %> alt="" />
    <%= form.label :upload_image %>
    <%= form.file_field :image %>
  </div>

  <div class="c-new-recipe-form__input-group">
    <div>
      <%= form.text_field :name, 
        class: "c-input",
        placeholder: "Enter the recipe name...", 
        required: true, 
        'aria-label': 'Recipe name' 
      %>
    </div>

    <div>
      <%= form.text_area :description,
        class: "c-input c-input--textarea",
        placeholder: "Enter the recipe description...", 
        required: true, 
        'aria-label': 'Description' 
       %>
    </div>

    <div>
      <%= form.label :preparation_time %>
      <%= form.number_field :preparation_time,
        class: "c-input",
        value: 0.25,
        step: 0.25,
        min: 0.25
       %>
    </div>

    <div>
      <%= form.label :cooking_time %>
      <%= form.number_field :cooking_time,
        class: "c-input",
        value: 0.25,
        step: 0.25,
        min: 0.25
      %>
    </div>


    <div>
      <%= form.label :public %>
      <%= form.check_box :public %>
    </div>
  </div>

  <div>
    <%= form.submit "Create Recipe", class: "c-btn c-btn--full c-btn--lg" %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div class="row border border-2 rounded rounded-2 mb-3 p-3">
	<div class="col d-flex flex-column justify-content-between">
		<span><%= link_to recipe.name, recipe, class: 'nav-link fs-4 fw-bold' %></span>
		<% if can? :destroy, recipe %>
			<%= link_to 'REMOVE', [recipe], method: :delete, data: {confirm: 'Are you sure!'}, class: 'fs-6 text-decoration-none' %>
		<% end %>
	</div>
	<div class="col-10">
		<span><%= recipe.description %></span>
	</div>
</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<section class="my-3 p-3">
	<% @recipes.each do |recipe| %>
		<% if recipe.public? %>
			<%= render 'recipe', recipe: recipe %>
		<% end %>
	<% end %>

	<%= link_to 'New Recipe', new_recipe_path, class: 'btn btn-outline-dark btn-sm' %>
</section>

app/views/recipes/list_public.html.erb
<section class="p-recipes">
  <header class="p-recipes__header c-card">
    <h1 class="c-section-title">
      Public recipes
    </h1>
    <span class="p-recipes__count">
      <%= pluralize(@recipes.length, 'item') %>
    </span>
  </header>

  <% if @recipes.empty? %>
    <p>
      There are no public recipes. Be the first to publish one!
    </p>
  <% else %>
    <div class="c-recipes-grid" id="recipes">
      <% @recipes.each do |recipe| %>
        <%= render recipe %>
      <% end %>
    </div>
  <% end %>
</section>

app/views/recipes/new.html.erb
<br>
<h2 class="text-center">Add New Recipe</h2>
<br>
<%= form_with model: @recipe do |f| %>
	<div>
		<%= f.label :public %>
		<%= f.select :public, options_for_select([['true', true], ['false', false]], selected: true) %>
	</div>
	<br>
	<div>
		<%= f.label :name %>
		<%= f.text_field :name, autofocus: true, autocomplete: 'name', placeholder: 'name', class: 'form-control' %>
	</div>
	<br>
	<div>
		<%= f.label :cooking_time, "Cooking Time" %>
		<%= f.text_field :cooking_time, autofocus: true, autocomplete: 'cooking_time', placeholder: 'Cooking time', class: 'form-control' %>
	</div>
	<br>
	<div>
		<%= f.label :preparation_time, "Preparation Time" %>
		<%= f.text_field :preparation_time, autofocus: true, autocomplete: 'preparation_time', placeholder: 'Preparation time', class: 'form-control' %>
	</div>
	<br>
	<div>
		<%= f.label :Description %>
		<%= f.text_area :description, autofocus: true, autocomplete: 'description', placeholder: 'description', class: 'form-control' %>
	</div>
	<br>
	<div>
		<%= f.number_field :user_id, value: current_user.id, type: :hidden %>
	</div>
	<br>
	<div>
		<%= f.submit class: 'btn btn-outline-dark btn-sm' %>
	</div>
<% end %>

app/views/recipes/shopping_list.html.erb
<br>
<h2 class="text-center">Shopping List</h2>
<section>
  <div class="d-flex justify-content-between align-items-center">
    <div>
      <p>Amount of food to buy: <%= @missing_foods.count %></p>
      <p>Total value of food needed: $<%= @missing_foods.sum {|food| food.food.price } %> </p>
    </div>
    <div>
      <p>Inventory: <%= link_to @recipe.name, recipe_path(@recipe) %></p>
      <p>Inventory: <%= link_to @inventory.name, inventory_path(@inventory) %></p>
    </div>
  </div>
  <table class="table table-striped table-bordered">
    <% if @missing_foods.any? %>
      <thead>
        <tr>
          <th scope="col">Food</th>
          <th scope="col">Quantity</th>
          <th scope="col">Price</th>
        </tr>
      </thead>
      <tbody>
      <% @missing_foods.each do |food| %>
        <tr>
          <td><%= food.food.name%></td>
          <td><%= food.quantity%> <%= food.quantity_unit%></td>
          <td><%= food.food.price%></td>
        </tr>
      <% end %>
      </tbody>
    <% end %>
  </table>
</section>

app/views/recipes/show.html.erb
<section>
	<% if @recipe.public? || @recipe.user == current_user %>
		<h2 class="text-center mb-3"><%= @recipe.name %></h2>
		<div class="d-flex justify-content-between align-items-center mb-3">
			<span>Preparation Time: <%= @recipe.preparation_time %></span>
			<%= form_with(model: @recipe, url: recipe_path(@recipe), method: :patch, id: 'recipe-form') do |form| %>
				<div class="form-check form-switch form-check-reverse">
					<%= form.check_box :public, class: 'form-check-input', id: 'toggle-btn', data: { public: @recipe.public } %>
					<%= form.label :public, class: 'form-check-label' %>
				</div>
			<% end %>
		</div>
		<span class="d-block mb-3">Cooking Time: <%= @recipe.cooking_time %></span>
		<span>Steps goes here...</span>
		<div class="d-flex justify-content-between align-items-center mt-3">
			<button type="button" class="btn btn-outline-dark btn-sm" data-bs-toggle="modal" data-bs-target="#exampleModal">
				Generate shopping list
			</button>
			<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<h1 class="modal-title fs-5" id="exampleModalLabel">Generate shopping list</h1>
							<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
						</div>
						<div class="modal-body">
							<span>Choose an inventory to use</span>
							<%= form_with(url: shopping_list_path, method: :get) do |f| %>
								<div class="d-flex justify-content-between align-items-center mt-3">
									<div>
										<%= f.hidden_field :recipe_id, value: @recipe.id %>
										<%= f.collection_select :inventory_id, @inventories, :id, :name, { prompt: '.. Select Inventory ..' }, id: 'inventory-select' %>
									</div>
									<div><%= f.submit 'Generate', class: 'btn btn-outline-dark btn-sm' %></div>
								</div>
							<% end %>
						</div>
					</div>
				</div>
			</div>
			<% if can? :new, @recipe %>
				<%= link_to 'Add ingredient', new_recipe_recipe_food_path(recipe_id: @recipe_id), class: 'btn btn-outline-dark btn-sm' %>
			<% end %>
		</div>
	<% end %>
	<hr/>
	<table class="table table-striped table-bordered">
		<% if @recipe.recipe_foods.any? %>
			<thead>
				<tr>
					<th scope="col">Food</th>
					<th scope="col">Quantity</th>
					<th scope="col">Value</th>
					<th scope="col">Actions</th>
				</tr>
			</thead>
			<tbody>
			<% @recipe.recipe_foods.each do |food_recipe| %>
				<tr>
					<td><%=food_recipe.food.name %></td>
					<td><%=food_recipe.quantity %> <%=food_recipe.quantity_unit %></td>
					<td>$<%=food_recipe.quantity * food_recipe.food.price %></td>
					<td>
						<%= link_to 'Modify', edit_recipe_recipe_food_path(@recipe, id: food_recipe), class: 'me-1' %>
      			<%= link_to 'Remove', recipe_recipe_food_path(@recipe, id: food_recipe), method: :delete, data: { confirm: 'Are you sure?' } %>
					</td>
				</tr>
			<% end %>
			</tbody>
		<% end %>
	</table>
</section>
<%= javascript_include_tag 'recipes' %>